// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo8g6_HYXGFA-dtesbuv3p5htolb4cRSE',
    appId: '1:341565608443:web:456943519b5fb767c87b5e',
    messagingSenderId: '341565608443',
    projectId: 'gymforlife-fe532',
    authDomain: 'gymforlife-fe532.firebaseapp.com',
    databaseURL: 'https://gymforlife-fe532.firebaseio.com',
    storageBucket: 'gymforlife-fe532.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE3IoicIBEYQuwxoKkQsXzaYQl4RQjY6M',
    appId: '1:341565608443:android:2d97f37cc8c43191c87b5e',
    messagingSenderId: '341565608443',
    projectId: 'gymforlife-fe532',
    databaseURL: 'https://gymforlife-fe532.firebaseio.com',
    storageBucket: 'gymforlife-fe532.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpg_IAPSePN-R_9xYA_B2xhn4P-DJjwKY',
    appId: '1:341565608443:ios:26432be12e35866cc87b5e',
    messagingSenderId: '341565608443',
    projectId: 'gymforlife-fe532',
    databaseURL: 'https://gymforlife-fe532.firebaseio.com',
    storageBucket: 'gymforlife-fe532.appspot.com',
    androidClientId: '341565608443-3cdjskrou3antr262tikugrqe472md26.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpg_IAPSePN-R_9xYA_B2xhn4P-DJjwKY',
    appId: '1:341565608443:ios:f5c11e6f92f54849c87b5e',
    messagingSenderId: '341565608443',
    projectId: 'gymforlife-fe532',
    databaseURL: 'https://gymforlife-fe532.firebaseio.com',
    storageBucket: 'gymforlife-fe532.appspot.com',
    androidClientId: '341565608443-3cdjskrou3antr262tikugrqe472md26.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskList.RunnerTests',
  );
}
